### ISSUE TITLE
Seed scripts missing

### ISSUE THREAD

**Issue by zsiddiqi** [ustwo/react-project-base#3]
Hi,

Appreciate the fixes done last time around. The project now builds and runs. However, without any sample seed data, the App page only displays "App Example" on the blank index page.

Would it be possible to commit the sample seed scripts so that we could see something more useful than the two words coded in the view component. Otherwise, what is the point of linking the rethinkdb via docker?

Your help would be much appreciated. Cheers

**Comment by ch2ch3** [comment]
Hey @zsiddiqi!

Coincidentally, we've recently been having some internal discussions around the scope of this project base as we have another project with a fairly similar setup (https://github.com/ustwo/docker-node-boilerplate) which was more recently updated.

Is rethinkdb of specific interest to you? I'm happy to set up a quick example sometime today or tomorrow.

**Comment by zsiddiqi** [comment]
Hi Ethel,

I am delighted to hear from you, it would be interesting to find out how
this base project has been scoped by your team internally. Also, I did look
at the new docker-node-boilerplate that you mentioned which looks quite
promising.

As for rethinkdb, I am looking into using it for my next project and that
is why I wanted a base that would have support built into it. Would be
great if you could share some example seed data to go with the react base
project since the tasks script already has associated commands to load the
seed data. Are you guys using rethinkdb a lot in your projects?

Thanks for your help and support, much appreciated.

Cheers
Zafar.

**Comment by ch2ch3** [comment]
Hi @zsiddiqi,

I've added some examples now, and the `README` has been updated with more info. You'll probably need to rebuild the project as some dependencies have changed, and you can use `t seed` to seed `rethink` with dummy data once the project has built.
